onlinedemo2/online/urls.py
from django.urls import path

from online import views
app_name="online"

urlpatterns = [
    path('',views.productlistview.as_view(),name='list'),
    path('<int:pk>/',views.productdetailsview.as_view(),name='detail'),
]

onlinedemo2/onlinedemo2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online.urls')),
]

onlinedemo2/online/models.py
from django.db import models

# Create your models here.
from django.urls import reverse

class Product(models.Model):
    name=models.CharField(max_length=268)
    price=models.IntegerField()
    warrenty=models.IntegerField()
    waterRes=models.CharField(max_length=268)
    display=models.CharField(max_length=268)
    image=models.ImageField(upload_to='images/')
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("online:detail",kwargs={'pk':self.pk})


class Customer(models.Model):
    name=models.CharField(max_length=268)
    home=models.CharField(max_length=268)
    area=models.CharField(max_length=268)
    town=models.CharField(max_length=268)
    state=models.CharField(max_length=268)
    pin=models.IntegerField()

    def __str__(self):
        return self.name

onlinedemo2/online/views.py
from django.shortcuts import render
from .models import Product,Customer
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)

# Create your views here.
class productlistview(ListView):
    model=Product

class productdetailsview(DetailView):
    context_object_name = 'school_details'
    model = Product
    # template_name = 'online/product_detail.html'
    template_name='online/product_list.html'

onlinedemo2/online/templates/online/product_app_base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {# Title Extensions go inside the block#}
      {% block title_block %}

      {% endblock %}
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="">Admin</a></li>
           <li><a class="navbar-link" href="{% url 'online:list' %}">Home</a></li>
        </ul>
    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}


  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.2.0.min.js"
  integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
  crossorigin="anonymous"></script>
</html>

onlinedemo2/online/templates/online/product_detail.html
{% extends "online/product_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the Product Detail Page</h1>
    <h2>Product Details:</h2>
    <p>Id_num: {{product_details.id}}</p>
    <p>Name: {{product_details.name}}</p>
    <p>Price: {{product_details.price}}</p>
    <p>Warrenty: {{product_details.warrenty}}</p>
    <p>Water Resistance: {{product_details.waterRes}}</p>
    <p>Display: {{product_details.display</p>




  </div>
  <div class="container">
        <p><a class='btn btn-warning' href="{% url 'online:update' pk=product_details.pk %}">Update</a></p>

  </div>

{% endblock %}

onlinedemo2/online/templates/online/product_list.html
{% extends "online/product_app_base.html" %}
{% block body_block %}

  <div class="jumbotron">

    <h1>Welcome to the Shopping World!!!!!</h1>
      <ol>
        {% for product in object_list %}
           <div class="col-sm-6 col-md-4">
                <div class="thumbnail">

                    <img src="{{ product.image.url}}"  width="240" height="240">


                  <div class="caption">
                    <h3>{{ product.name }}</h3>
                    <h3>{{ product.price }}</h3>
                    <p>...</p>
                    <p><a href="{% url 'online:detail' pk=product.pk %}" class="btn btn-primary" role="button">View</a> </p>
                  </div>
                </div>
           </div>

        {% endfor %}
      </ol>

  </div>



{% endblock %}